### ISSUE TITLE
Page navigation depends on jquery.com

### ISSUE THREAD

**Issue by mryellow** [GlacierProtocol/glacierprotocol.github.io#12]
With 3rd party javascript blocked the site fails to function.

It should gracefully degrade or host these assets locally to avoid 3rd party trust issues on this type of site.

**Comment by diogomonica** [comment]
Agreed, this would be ideal, but using the PDF (or a printed version) is the recommended way of actually following the protocol. The web-version is provided for the convenience of the initial understanding/learning of how the protocol works.

**Comment by mryellow** [comment]
Any site should function without 3rd party assets.
