### ISSUE TITLE
Seed words

### ISSUE THREAD

**Issue by dimaatmelodromru** [GlacierProtocol/glacierprotocol.github.io#46]
Consider updating [_docs/deposit/transfer-to-paper.md](https://GlacierProtocol.github.io/docs/deposit/transfer-to-paper/), because many people are interested in using (possibly memorizing) 12/24 seed words, could you please cover this option in your protocol?

**Comment by bitcoinhodler** [comment]
Unfortunately that's not really an option, given the way Glacier does things today. Seed words are used for HD keys (via the BIP39 standard) which Glacier doesn't support.

There is some movement towards using HD keys in Glacier but there are many steps to get from here to there.

It is conceivable we could use the recent SLIP39 standard, which can convert any binary blob into a word list, to convert each WIF key to a word list, but that's non-standard and would therefore be rather confusing.

**Comment by dimaatmelodromru** [comment]
I don't need multisig. I just want to get a 24 or better 12 words list, memorize it and later use a stateless hardware device like this https://github.com/justinmoon/bitboy to sign withdrawal txs.
Can you advise on how do I achieve that?

>

**Comment by bitcoinhodler** [comment]
That sounds like the way every hardware wallet works, except for the stateless part.

You could use a hardware wallet to generate a key, write down the seed words, get a receiving address from the HW, then do a factory reset on the HW. Next time you want to spend those coins, you initialize the HW by doing a recovery using the seed words.

I'd consider this rather reckless though -- if you lose that piece of paper, or memorize it and then forget it, your money is gone forever.

**Comment by dimaatmelodromru** [comment]
You cannot forget all the words)
You cannot forget them at all if you have to enter them periodically in a stateless PSBT-signing device.
People memorize Torah and Quran, for God's sake)))
And you have to remember your hw passphrase and where you’ve left it anyway. And you can have it stolen or confiscated. 

Buy a HW wallet just to generate a wallet? Can’t I use the standard bitcoin core for that? And not worry about source of entropy in hw, implementation of HD derivation, etc?

I’d rather use a raspberry. 

>

**Comment by bitcoinhodler** [comment]
I'm not sure I follow all your objections.

Google for "brain wallet" and you will find many ways to accomplish your goal, but I would say a reputable hardware wallet, sourced from the manufacturer directly, is the most secure. You could also use Ian Coleman's [BIP39 JavaScript page](https://iancoleman.io/bip39/), transferred to an offline quarantined computer, and rolling casino dice to provide entropy.

Bitcoin Core does not support BIP39 or any other system of seed words. RaspPi4 has wireless networking hardware, which is a vulnerability.

Glacier is not intended to be a brain wallet.

**Comment by bitcoinhodler** [comment]
Closing as not relevant to Glacier (at least, not before we do HD multisig).
